_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 0325c4c5-136f-4ccc-86e8-e4140c7f75ea
name: 'Github Actions Test'
mail: bc-bot@bluecadet.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
