name: Pull Request Action
on:
  push:
    branches:
      - "feature/slack-notifications"
  workflow_dispatch:
  schedule:
    - cron: "5 17 * * 1-5"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto_pr:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code.
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #     ref: ${{ github.head_ref || github.ref_name }}

      - name:
        # run: gh pr create -B test -H bluecadet --title ''
        run: gh pr create --repo bluecadet/panth-github-actions -B feature/target -H feature/slack-notifications --title 'This is a PR bwahhaha' --body "Daily merge" --assignee pingevt --reviewer pingevt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
