name: Pantheon Backups w/ Terminus
on:
  schedule:
    - cron: '15 15 * * *' #UTC

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:

    # Install Terminus.
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Backup Live
      run: terminus backup:create panth-github-actions.live --keep-for=15 -n -q &

    - name: Backup Test
      run: terminus backup:create panth-github-actions.test --keep-for=15 -n -q &

    - name: Backup Dev
      run: terminus backup:create panth-github-actions.dev --keep-for=15 -n -q &
