name: Deploy to Pantheon
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Use Node.js 14.
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.0
    - name: node builder
      run: |
        npm install
        npm run out
        gulp build
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add pantheon $pantheon_repo
        git add .
        git commit -q -m 'Build assets for dev.'
        git push pantheon HEAD:master
