name: Deploy to Pantheon
on: push

# env:
#   TZ: "/usr/share/zoneinfo/America/New_York"
#   TERM: dumb
#   ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
#   ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
#   ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
#   GITHUB_TOKEN: ${{ github.token }}
#   TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
#   TEST_SITE_NAME: ${{ secrets.TERMINUS_SITE }}
#   CI_BRANCH: ${{ github.head_ref || github.ref_name }}
#   COMMIT_SHA: ${{ github.sha }}
#   CI_BUILD_NUMBER: ${{ github.run_number }}
#   DEFAULT_SITE: ${{ secrets.TERMINUS_SITE }}
#   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#   GITHUB_OWNER: ${{ github.repository_owner }}
#   CI_PROJECT_NAME: ${{ github.repository }}
#   PR_NUMBER: ${{ github.event.number }}
#   CI_PULL_REQUEST: ${{ github.event.pull_request._links.html.href }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # Install Terminus.
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Install Terminus Build Tools
      run: terminus self:plugin:install terminus-build-tools-plugin

    # Check Terminus works.
    - name: Update Ignore File.
      run: terminus build:gitignore:cut

    # - name: Use Node.js 14.
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 14.19.0

    # # Cache vendor folder
    # - name: Cache vendor folder
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-vendor
    #   with:
    #     path: ./vendor
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

    # - name: node builder
    #   run: |
    #     npm install
    #     npm run out
    #     gulp build

    # - name: deployer
    #   env:
    #     pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
    #   run: |
    #     git remote add pantheon $pantheon_repo
    #     git config user.mail "bc-bot@bluecadet.com"
    #     git config user.name "Bluecadet Bot"
    #     git rm `cat .gitignore-panth`
    #     cat .gitignore-panth >> .gitignore
    #     git add .
    #     git commit -q -m 'Build assets for dev.'
    #     git push --force pantheon HEAD:master
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add pantheon $pantheon_repo
        git push --force pantheon HEAD:master

    # - name: Wait for Pantheon to fully sync code
    #   run: terminus workflow:wait panth-github-actions.dev --max=6000

